version: '3.8'

services:
  girlfriend-alert:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Add your VAPID keys here or use .env file
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    volumes:
      # Optional: Mount .env file
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if using HTTPS
      # - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - girlfriend-alert
    restart: unless-stopped
    profiles:
      - proxy

# Optional: Create named volume for persistent data
volumes:
  app_data:
